force-app/main/default/objects/DependencyPicklist__mdt/DependencyPicklist__mdt.object-meta.xml
<CustomObject>
    <label>DependencyPicklist</label>
    <pluralLabel>DependencyPicklists</pluralLabel>
</CustomObject>

force-app/main/default/objects/DependencyPicklist__mdt/fields/Recordtype__c.field-meta.xml
<CustomField>
    <fullName>Recordtype__c</fullName>
    <label>Recordtype</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DependencyPicklist__mdt/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>SubType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DependencyPicklist__mdt/fields/Tool__c.field-meta.xml
<CustomField>
    <fullName>Tool__c</fullName>
    <label>Tool</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DependencyPicklistController.cls
public with sharing class DependencyPicklistController {


 @AuraEnabled(cacheable=true)
 public static list<DependencyPicklist__mdt> getPicklistValues(){

    list<DependencyPicklist__mdt> lstDp = new list<DependencyPicklist__mdt>();
    
    try {
        
      lstDp = [SELECT id, Recordtype__c, SubType__c, Tool__c, Type__c FROM DependencyPicklist__mdt];
   
    } catch (Exception e) {
        throw new AuraHandledException(JSON.serialize(e.getMessage()));
    }

    return lstDp;
 }

 @AuraEnabled
 public static String saveRecord(String recordId, String wrapperValues){

  String msgResult;

  try {
    
    wrapperFields Fields = (wrapperFields) JSON.deserializeStrict(wrapperValues, wrapperFields.class);
    system.debug('Fields =' + Fields);

    system.debug('recordId =' + recordId);
    Case caseUpsert = new Case(id = recordId);
    caseUpsert.Recordtype__c = Fields.recordtype;
    caseUpsert.SubType__c = Fields.subtype;
    caseUpsert.Tool__c = Fields.tool;
    caseUpsert.Type__c = Fields.type;
    system.debug('caseUpsert =' + caseUpsert);
    upsert caseUpsert;
    msgResult = 'success';
  } catch (Exception e) {
    throw new AuraHandledException(e.getMessage());
  }

  return msgResult;

 }

 public class wrapperFields{
   public String recordtype;
   public String subtype;
   public String tool;
   public String type;
 }
}